services:
  - type: web
    name: telegram-test-bot-3
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN_BOT2
        sync: false
      - key: GOOGLE_DRIVE_FILE_ID
        sync: false
    
